[workspace]

members = [
        "comments", "control_flow",
        "data_types",
        "functions",
        "guessing_game",
        "hello_cargo",
        "hello_world",
        "variables",
]

resolver = "2"
